#pragma once
void starline();
void file_s4et4ik_l();
void file_s4et4ik_Bus2();
int check_price(float t);
int check_menu(int counter);
float check_for_price();
void check_for_string(char* str);
void check_for_ready(char* str);
void check_for_date(char* str);
void check_for_telephone(char* str);
int user_menu();
int admin_menu();
void verification();
void file_l();
void add_l();
void printf_table_l(struct User* array, int len);
void change_log();
void del_log();
void file_b();
void file_read_b2();
void file_find(int i, int count);
void enter_new();
void print_table(struct Product* array, int len);
void del();
void change();
void add_more();
int menu_find();
void find_telephone(char* punkt);
void find_ready(char* num);
void find_FIO(char* type);
void find();
int menu_sort();
void sort_price_up();
void sort_ready();
void sort_type();
void sort();
int set_color();

